spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      static-locations: classpath:/static/